### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by stefblue83** [bram-is/homebridge-slide-shutter#7]
Hello,

First thank you very much for the great work so far. The plugin was working fine till I added a second slide.

My setup:
Raspberry PI with Hoobs - https://hoobs.org/ - version 3.3.5 
Latest plugin 1.0.1 
Apple Homekit etc
2 slides in single room left and right - I named them Links & Rechts (I'm German)
I started with one and all was working I purchased the second one later   

After I added the second one the Bridge started to crash:

13.5.2021, 18:48:39 [slide-shutter] Adding new accessory: Links
13.5.2021, 18:48:39 [slide-shutter] Slide shutter initialised!
13.5.2021, 18:48:39 [slide-shutter] Adding new accessory: Rechts
13.5.2021, 18:48:39 [slide-shutter] Slide shutter initialised!
13.5.2021, 18:48:39 (node:2530) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: **xyz-891b-7ec2d0257b3a**
13.5.2021, 18:48:39 at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
13.5.2021, 18:48:39 at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:593:12)
13.5.2021, 18:48:39 at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:481:21)
13.5.2021, 18:48:39 at HomebridgeAPI.emit (events.js:315:20)
13.5.2021, 18:48:39 at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/src/api.ts:340:10)
13.5.2021, 18:48:39 at SlidePlatform.registerDevices (/home/hoobs/.hoobs/node_modules/homebridge-slide-shutter/src/platform.ts:162:18)
13.5.2021, 18:48:39 at SlidePlatform.discoverRemoteDevices (/home/hoobs/.hoobs/node_modules/homebridge-slide-shutter/src/platform.ts:111:12)
13.5.2021, 18:48:39 (Use `node --trace-warnings ...` to show where the warning was created)
13.5.2021, 18:48:39 (node:2530) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
13.5.2021, 18:48:39 (node:2530) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

It seems the plugin adds both in with the same UUID which then fails. Since I don't know the details I need for the manual config I was stuck on API. The cache looks strange too me after switching them 

$ cat cachedAccessories 
[{"plugin":"homebridge-slide-shutter","platform":"slide-shutter","context":{"device":{"name":"**Links**","id":6190,"deviceId":"slide_98F4AB1FE380","ip":null,"code":null,"pollInterval":null,"tolerance":null}},"displayName":"**Links**","UUID":"**xyz-7ec2d0257b3a"**,"category":1,"services":

$ cat cachedAccessories 
[{"plugin":"homebridge-slide-shutter","platform":"slide-shutter","context":{"device":{"name":"**Rechts**","id":6673,"deviceId":"slide_98F4AB026818","ip":null,"code":null,"pollInterval":null,"tolerance":null}},"displayName":"**Links**","UUID":"**xyz-891b-7ec2d0257b3a**","category":1,"services":

Restarting with this corrupted cache will lead to a sigfault - I need to disable the API - delete the cache or disconnect from Apple.

    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "slide-shutter",
            "plugin_map": {
                "plugin_name": "homebridge-slide-shutter"
            },
            "name": "slide-shutter",
            "remote": false,
            "username": "xxx",
            "password": "xxx",
            "devices": []
        }

While pulling the data it needs to store them with different UUIDs to work.

Thanks!

**Comment by bramsmulders** [comment]
Hi @stefblue83 thanks for the detailed bug report! 

I see that your both slides are added with the same UUID. After some investigation i've found the bug and fixed it in [v1.0.2](https://github.com/bram-is/homebridge-slide-shutter/releases/tag/v1.0.2).
